#
# COMO USAR:
#
# export KONG_LICENSE_DATA='......'  # deixe vazia se for rodar em free mode
# docker-compose up -d kong-db
# docker-compose up kong-init
# docker-compose up kong
#
# KONG MANAGER: http://localhost:8002
#
# Importante: em free mode não existe o Dev Portal
#
version: "3"

services:
  kong-db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - kongdb:/var/lib/postgresql
  kong-init:
    image: kong/kong-gateway:2.5.0.1
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: vert1234
      KONG_PG_DATABASE: kong
      KONG_LOG_LEVEL: debug
    command: kong migrations bootstrap
  kong:
    image: kong/kong-gateway:2.5.0.1
    depends_on:
      - kong-db
      - kong-init
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PORTAL_GUI_HOST: localhost:8003
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PORTAL: "on"
      KONG_PORTAL_AUTH: basic-auth
      KONG_PORTAL_AUTO_APPROVE: "on"
      KONG_PORTAL_SESSION_CONF: "{\"cookie_name\":\"portal_session\",\"cookie_samesite\":\"Strict\",\"secret\":\"myportalsessionid\",\"cookie_secure\":false,\"storage\":\"kong\",\"cookie_domain\":\"localhost\"}"
      # RBAC SÓ FUNCIONA COM LICENÇA, SEM LICENÇA TEMOS FREE MODE
      # AS CONFIGS ABAIXO SÃO INÓCUAS EM FREE MODE
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_CONF: "{\"cookie_name\":\"admin_session\",\"cookie_samesite\":\"off\",\"secret\":\"myadminsessionsecret\",\"cookie_secure\":false,\"storage\":\"kong\",\"cookie_domain\":\"localhost\"}"
      KONG_ENFORCE_RBAC: "on"
      KONG_LOG_LEVEL: notice
      KONG_LICENSE_DATA: "${KONG_LICENSE_DATA}"
      # AS CONFIGS ACIMA SÃO INÓCUAS EM FREE MODE
      # SMTP - DESCOMENTAR E USAR SEUS VALORES
      # KONG_SMTP_MOCK: "off"
      # KONG_SMTP_HOST: "smtp.mailtrap.io"
      # KONG_SMTP_PORT: 2525
      # KONG_SMTP_USERNAME: "1d5a2cc46a5657"
      # KONG_SMTP_PASSWORD: "93a80d99bba406"
      # KONG_SMTP_STARTTLS: "on"
      # KONG_SMTP_AUTH_TYPE: "login"
      # KONG_SMTP_ADMIN_EMAILS: "kong@vertigo.com.br"
      # KONG_ADMIN_EMAILS_FROM: "kong@vertigo.com.br"
      # KONG_ADMIN_EMAILS_REPLY_TO: "kong@vertigo.com.br"
      # KONG_PORTAL_EMAILS_FROM: "kong@vertigo.com.br"
      # KONG_PORTAL_EMAILS_REPLY_TO: "kong@vertigo.com.br"
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
volumes:
  kongdb:
