#
# Valores para testes em k3d local.
# Esta configuração assume que nomes "*.localhost" resolvem para localhost. Se não for o caso basta
# criar entradas manualmente em /etc/hosts .
#

image:
  repository: kong/kong-gateway
  tag: "3.5"
env:
  role: data_plane
  cluster_dp_labels: "environment:dev"
  cluster_control_plane: kong-kong-cluster.kong-cp.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-kong-clustertelemetry.kong-cp.svc.cluster.local:8006
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
secretVolumes:
- kong-cluster-cert
ingressController:
  enabled: false
  installCRDs: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 30000
  tls:
    enabled: false
  ingress:
    enabled: false
admin:
  enabled: false
manager:
  enabled: false
portal:
  enabled: false
portalapi:
  enabled: false
postgresql:
  enabled: false # cp já tem
