#
# Valores para testes em k3d local.
# Esta configuração assume que nomes "*.localhost" resolvem para localhost. Se não for o caso basta
# criar entradas manualmente em /etc/hosts .
#

image:
  repository: kong/kong-gateway
  tag: "3.6"
env:
  database: "off"
  admin_gui_url: "http://manager.localhost:8000/manager"
  admin_gui_path: "/manager"
  admin_gui_api_url: "http://manager.localhost:8000"
  log_level: notice
ingressController:
  enabled: true
  installCRDs: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 30000
  tls:
    enabled: true
    nodePort: 30001
  ingress:
    enabled: false
admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    #ingressClassName: "traefik"
    hostname: manager.localhost
    path: "/"
manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: manager.localhost
    #ingressClassName: "traefik"
    path: "/manager"
# portal e portalapi nao existem mais
portal:
  enabled: false
portalapi:
  enabled: false
# status
status:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
