#
# Valores para testes em k3d local.
# Esta configuração assume que nomes "*.localhost" resolvem para localhost. Se não for o caso basta
# criar entradas manualmente em /etc/hosts .
#

image:
  repository: kong/kong-gateway
  tag: "3.6"
env:
  database: postgres
  portal: off
  admin_gui_url: "http://manager.localhost:8000/manager"
  admin_gui_path: "/manager"
  admin_gui_api_url: "http://manager.localhost:8000"
  proxy_url: "http://localhost:8000"
  log_level: notice
ingressController:
  enabled: true
enterprise:
  enabled: true
admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: manager.localhost
    path: "/"
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
      konghq.com/plugins: admin-auth
proxy:
  type: LoadBalancer
  http:
    enabled: true
  tls:
    enabled: true
  ingress:
    enabled: false
manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: manager.localhost
    path: "/manager"
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/plugins: admin-auth
portal:
  enabled: false
portalapi:
  enabled: false
status:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
postgresql:
  enabled: true
