#
# Valores para testes em k3d local.
# Esta configuração assume que nomes "*.localhost" resolvem para localhost. Se não for o caso basta
# criar entradas manualmente em /etc/hosts .
#

image:
  repository: kong/kong-gateway
  tag: "3.5"
secretVolumes:
- kong-cluster-cert
env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  database: postgres
  pg_host: "kong-postgresql"
  pg_user: kong
  pg_password: kong
  pg_database: kong
  pg_port: 5432
  portal: off # nao existe mais
  admin_gui_url: "http://localhost:30002"
  admin_gui_path: "/"
  admin_gui_api_url: "http://localhost:30001"
  proxy_url: "http://localhost:8000"
  # ambos off = data plane
  proxy_listen: "off"
  stream_listen: "off"
  log_level: debug
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password
ingressController:
  enabled: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    session_conf_secret: kong-session-config
cluster:
  enabled: true
  type: NodePort
  tls:
    enabled: true
    nodePort: 30005
clustertelemetry:
  enabled: true
  type: NodePort
  tls:
    enabled: true
    nodePort: 30006
    type: ClusterIP
proxy:
  enabled: false
admin:
  enabled: true
  http:
    enabled: true
    nodePort: 30001
  tls:
    enabled: false
  ingress:
    enabled: false
manager:
  enabled: true
  http:
    enabled: true
    nodePort: 30002
  tls:
    enabled: false
  ingress:
    enabled: false
status:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
portal:
  enabled: false
portalapi:
  enabled: false
postgresql:
  enabled: true
  auth:
    username: kong
    password: kong
    database: kong
