#
# Valores para deploymrnt do Kong Gateway no Okteto (free mode).
#

image:
  repository: kong/kong-gateway
  #tag: "2.8"
env:
  database: postgres
  pg_host: "kong-postgresql"
  pg_user: kong
  pg_password: kong
  pg_database: kong
  pg_port: 5432
  portal: off
  admin_gui_url: "https://kong-kong-manager-NAMESPACE.cloud.okteto.net"
  admin_api_uri: "https://kong-kong-admin-NAMESPACE.cloud.okteto.net"
  proxy_url: "https://kong-kong-proxy-NAMESPACE.cloud.okteto.net"
  log_level: notice
ingressController:
  enabled: false
  installCRDs: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  smtp:
    disabled: true
admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: false
  annotations:
    dev.okteto.com/auto-ingress: "true"
proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: false
  annotations:
    dev.okteto.com/auto-ingress: "true"
manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: false
  annotations:
    dev.okteto.com/auto-ingress: "true"
portal:
  enabled: false
portalapi:
  enabled: false
status:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
postgresql:
  enabled: true
  auth:
    username: kong
    password: kong
    database: kong
  primary:
    persistence:
      size: 2Gi
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

