#
# Valores para testes em k3d local.
#

image:
  repository: kong
  tag: "3.5"
env:
  admin_gui_api_url: "http://localhost:9000"
  admin_gui_url: "http://localhost:9001"
  proxy_url: "http://localhost:8000"
  log_level: debug
ingressController:
  enabled: true
  # image:
  #   repository: kong/kubernetes-ingress-controller
  #   tag: "3.0"
enterprise:
  enabled: false
admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 30000 # vkpr nodeport exposed as 9000
  tls:
    enabled: false
proxy:
  type: LoadBalancer # vkpr LB
  http:
    enabled: true
  tls:
    enabled: false
manager:
  # Enable creating a Kubernetes service for Kong Manager
  enabled: true
  type: NodePort
  http:
    enabled: true
    nodePort: 30001 # vkpr nodeport exposed as 9001
  tls:
    enabled: false
